### ISSUE TITLE
Logs do not correlate (nest) with request logs properly

### ISSUE THREAD

**Issue by cmeil** [mtraver/gaelog#1] opened 2019-09-20 17:08 UTC
This might be better submitted as separate issues, in case they are unrelated, but I am using the go112 runtime with the standard app engine environment (not flex) and v0.1.2 of gaelog and observe the following:

1. The log output may appear duplicated -- once, nested in the request log, and again, as a separate log entry. 

2. The log output may not be correlated (nested) with its parent request and only appear as a separate entry. I'm not sure if this is timing related, but for example, when I use the Advanced REST Client chrome plugin to perform an HTTP GET request, the latency is generally a bit greater (vs. just accessing a URL from Chrome directly) and the log is not nested within its parent request (as it is with the now-deprecated appengine/log library).

3. When the log output IS nested within its parent request, the severity of the log is not propagated to the parent request (as it is with the now-deprecated appengine/log library).

**Comment by mtraver** [comment] 2019-09-20 17:59
1. This may be a result of how you're displaying logs in Stackdriver. If you choose "All logs" in the dropdown (or really if the selection includes "app_log", as that's the default log name used by this package) then you'll see them as independent entries as well as nested under requests. If the selection includes "appengine.googleapis.com/request_log" and does not include "app_log" then you'll only see them nested under the request logs.

2. I've noticed this as well. Sometimes the logs aren't nested. My instinct is that it's a display issue in Stackdriver, but I haven't investigated much. The way that logs are correlated is through their `MonitoredResource` and trace ID.

  - `MonitoredResource`: https://github.com/mtraver/gaelog/blob/194026198cadc81d9d7e1b2dbd362995ece95ee2/gaelog.go#L93
  - trace ID: https://github.com/mtraver/gaelog/blob/194026198cadc81d9d7e1b2dbd362995ece95ee2/gaelog.go#L106

If those values are set correctly in the log entry (i.e. they match their parent request) then they _should_ be correlated in the UI. Can you check if those values look correct in your logs? If they don't then there's a bug in this package.

3. This is a known issue. It annoys me too. I believe it's because the user-created log entries and the request log entries are created independently of each other. Logs created using the appengine/log library could be referenced when the request log entry was made, so the request entry's level could be set to the max of the sub-entrys' levels. There seem to be two remedies:

  - Edit the level of the request log once we have all the sub-logs. I don't think an API that can do this exists.
  - This package could produce request logs. That way this package can set the level of the request log appropriately like the old App Engine API did. I haven't thought this through thoroughly but it seems feasible. Could be provided as an option.

**Comment by cmeil** [comment] 2019-09-20 20:48
> 1. This may be a result of how you're displaying logs in Stackdriver. If you choose "All logs" in the dropdown (or really if the selection includes "app_log", as that's the default log name used by this package) then you'll see them as independent entries as well as nested under requests.

Yes, this is the case. Unfortunately, though, because of issue 2 (the logs not always being nested), I will miss some logs if I only show the request_log.

> If those values are set correctly in the log entry (i.e. they match their parent request) then they _should_ be correlated in the UI. Can you check if those values look correct in your logs?

They match in both cases (nested correctly and not nested). Perhaps it is a timestamp issue. From https://godoc.org/cloud.google.com/go/logging: 

> A child entry's timestamp must be within the time interval covered by the parent request (i.e., older than parent.Timestamp, and newer than parent.Timestamp - parent.HTTPRequest.Latency, assuming the parent timestamp marks the end of the request.

**Comment by cmeil** [comment] 2019-09-20 21:07
I stumbled across another example of someone else attempting to nest the child logs here and they do force the timestamp to time.Now(). See main.go in https://medium.com/google-cloud/combining-correlated-log-lines-in-google-stackdriver-dd23284aeb29

**Comment by mtraver** [comment] 2019-09-21 04:01
Aha! An excellent discovery. I've explicitly set the timestamp and released v0.1.3.

**Comment by cmeil** [comment] 2019-09-21 15:24
> Aha! An excellent discovery. I've explicitly set the timestamp and released v0.1.3.

Thanks for the quick commit! It works better -- but still not 100% :-(  In my limited testing so far, the logs were always nested correctly except for the initial request that loads the application for the first time (and thus has a much greater latency). I see in the example I linked to above that he also forces the HTTPRequest.Latency field, which starts to get ugly since it requires each request handler that writes logs to track the start time. I'm going to experiment with this to see if it makes a difference for that initial request.

An observation (with v0.1.3 of this package), is that the "timestamp" field of the parent and child requests are not the same as each other in the logs, even though setting the Timestamp field in the code did seem to make a difference. So I am not sure if the Stackdriver library is overwriting it at some point or if there is another internal timestamp being used for the log output or what.

**Comment by mtraver** [comment] 2019-09-23 16:06
Glad to hear it works at least a bit better. I think the only way to make it work flawlessly is to write request logs as well; `HTTPRequest.Latency` is only relevant for the request log.

It seems like correlating entries with the request logs that App Engine already writes has its limitations. I'll reproduce the loading request issue you mention and see if I can find a remedy though.

> An observation (with v0.1.3 of this package), is that the "timestamp" field of the parent and child requests are not the same as each other in the logs, even though setting the Timestamp field in the code did seem to make a difference. So I am not sure if the Stackdriver library is overwriting it at some point or if there is another internal timestamp being used for the log output or what.

I wouldn't expect them to be the same. In the request log, `timestamp` is the same as `protoPayload.startTime`. The `timestamp` of a nested entry is whenever that entry was created. 

The Stackdriver Logging docs (https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) say of `timestamp`, "If this field is omitted in a new log entry, then Logging assigns it the current time." But that would happen on the receiving end. Before we set the timestamp in the client I think it was possible for the time taken by log flushing, Stackdriver service latency, etc. to result in a timestamp outside the request's window.

**Comment by cmeil** [comment] 2019-09-23 17:56
So it appears the remaining (sub)issues (logs not necessarily nested on initial app engine load, and parent severity does not get set) are not really issues with this package. With the v0.1.3 release, I think this [issue](https://github.com/mtraver/gaelog/issues/1) may be closed. Thanks for sharing your work. It's the best I've found as a substitute for Google removing support for their appengine/log package.

**Comment by mtraver** [comment] 2019-09-25 23:37
Yes, I think that is so. I'll close it.

> logs not necessarily nested on initial app engine load

I understand this issue now. I looked at the timestamps of the entries not nested under the initial request, and they were within the request's window. The trace ID also matched, so they should have been nested. I realized that the only difference is that requests that start up a new instance have a log entry written by App Engine that says as much. So I tried using `google.golang.org/appengine/log` in addition to this package. Lo and behold, _none_ of the entries made by this package were correlated in the UI! Only the `google.golang.org/appengine/log` entries were. This doesn't seem correct. I'm going to open a bug with Stackdriver.

> Thanks for sharing your work.

Of course! Thank you for the testing and feedback.

**Closed as completed by mtraver** 2019-09-25 23:37 UTC
